convidados_noivo = set()
convidados_noiva = set()
convidados = input().split(';')
if convidados == 'ACABOU':
    print('-'*20)
    print(f'LISTA FINAL')
    print('-'*20)
    print()
    print()
    print('-'*20)
    print(f'APENAS NOIVA')
    print('-'*20)
    print()
    print()
    print('-'*20)
    print(f'APENAS NOIVO')
    print('-'*20)
    print()
    print()
    print('-'*20)
    print(f'POR AMBOS')
    print('-'*20)
    print()
    print()
    print('-'*20)
    print(f'POR APENAS UM DELES')
    print('-'*20)
    print()
else:
    while len(convidados) > 1:
        if convidados[1] == 'noivo':
            convidados_noivo.add(convidados[0])
            convidados = input().split(';')
        else: 
            convidados_noiva.add(convidados[0])
            convidados = input().split(';')

final = convidados_noivo.union(convidados_noiva)
print('-'*20)
print(f'LISTA FINAL')
print('-'*20)
lista = list(final)
lista.sort()
for items in lista:
    print(items)
print()
print('-'*20)
print(f'APENAS NOIVA')
print('-'*20)
apenas_noiva = convidados_noiva.difference(convidados_noivo)
listapenas_noiva = list(apenas_noiva)
listapenas_noiva.sort()
for items in listapenas_noiva:
    print(items)
print()
print('-'*20)
print(f'APENAS NOIVO')
print('-'*20)
apenas_noivo = convidados_noivo.difference(convidados_noiva)
listapenas_noivo = list(apenas_noivo)
listapenas_noivo.sort()
for items in listapenas_noivo:
    print(items)
print()
print('-'*20)
print(f'POR AMBOS')
print('-'*20)
ambos = convidados_noivo.intersection(convidados_noiva)
listaambos = list(ambos)
listaambos.sort()
for items in listaambos:
    print(items)
print()
print('-'*20)
print(f'POR APENAS UM DELES')
print('-'*20)
um_deles = convidados_noivo.symmetric_difference(convidados_noiva)
listaum_deles = list(um_deles)
listaum_deles.sort()
for items in listaum_deles:
    print(items)
